package treeniPaivaKirja.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import treeniPaivaKirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.25 22:48:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikkeetTest {



  // Generated by ComTest BEGIN
  /** testAnnaLiikkeet31 */
  @Test
  public void testAnnaLiikkeet31() {    // Liikkeet: 31
    Liikkeet treenit = new Liikkeet(); 
    Liike pitsi21 = new Liike(12); treenit.lisaa(pitsi21); 
    Liike pitsi11 = new Liike(11); treenit.lisaa(pitsi11); 
    Liike pitsi22 = new Liike(12); treenit.lisaa(pitsi22); 
    Liike pitsi12 = new Liike(11); treenit.lisaa(pitsi12); 
    Liike pitsi23 = new Liike(12); treenit.lisaa(pitsi23); 
    Liike pitsi51 = new Liike(15); treenit.lisaa(pitsi51); 
    List<Liike> loytyneet; 
    loytyneet = treenit.annaLiikkeet(3); 
    assertEquals("From: Liikkeet line: 44", 0, loytyneet.size()); 
    loytyneet = treenit.annaLiikkeet(11); 
    assertEquals("From: Liikkeet line: 46", 2, loytyneet.size()); 
    assertEquals("From: Liikkeet line: 47", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Liikkeet line: 48", true, loytyneet.get(1) == pitsi12); 
    loytyneet = treenit.annaLiikkeet(15); 
    assertEquals("From: Liikkeet line: 50", 1, loytyneet.size()); 
    assertEquals("From: Liikkeet line: 51", true, loytyneet.get(0) == pitsi51); 
  } // Generated by ComTest END
}