package treeniPaivaKirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treeniPaivaKirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.23 20:08:48 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikeTest {//todo
}