package treeniPaivaKirja.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import treeniPaivaKirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.25 23:08:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreeniPaivaKirjaTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa38() throws SailoException {    // TreeniPaivaKirja: 38
    TreeniPaivaKirja uusi = new TreeniPaivaKirja(); 
    Treeniohjelma aku1 = new Treeniohjelma(), aku2 = new Treeniohjelma(); 
    aku1.lisaaIdOhjelmalle(); aku2.lisaaIdOhjelmalle(); 
    assertEquals("From: TreeniPaivaKirja line: 43", 0, uusi.getTreeniOhjelmat()); 
    uusi.lisaa(aku1); assertEquals("From: TreeniPaivaKirja line: 44", 1, uusi.getTreeniOhjelmat()); 
    uusi.lisaa(aku2); assertEquals("From: TreeniPaivaKirja line: 45", 2, uusi.getTreeniOhjelmat()); 
    uusi.lisaa(aku1); assertEquals("From: TreeniPaivaKirja line: 46", 3, uusi.getTreeniOhjelmat()); 
    assertEquals("From: TreeniPaivaKirja line: 47", 3, uusi.getTreeniOhjelmat()); 
    assertEquals("From: TreeniPaivaKirja line: 48", aku1, uusi.annaOhjelma(0)); 
    assertEquals("From: TreeniPaivaKirja line: 49", aku2, uusi.annaOhjelma(1)); 
    assertEquals("From: TreeniPaivaKirja line: 50", aku1, uusi.annaOhjelma(2)); 
    try {
    assertEquals("From: TreeniPaivaKirja line: 51", aku1, uusi.annaOhjelma(3)); 
    fail("TreeniPaivaKirja: 51 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    uusi.lisaa(aku1); assertEquals("From: TreeniPaivaKirja line: 52", 4, uusi.getTreeniOhjelmat()); 
    uusi.lisaa(aku1); assertEquals("From: TreeniPaivaKirja line: 53", 5, uusi.getTreeniOhjelmat()); 
    try {
    uusi.lisaa(aku1); 
    fail("TreeniPaivaKirja: 54 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaTreenit95 */
  @Test
  public void testAnnaTreenit95() {    // TreeniPaivaKirja: 95
    TreeniPaivaKirja kerho = new TreeniPaivaKirja(); 
    Treeniohjelma aku1 = new Treeniohjelma(), aku2 = new Treeniohjelma(), aku3 = new Treeniohjelma(); 
    aku1.lisaaIdOhjelmalle(); aku2.lisaaIdOhjelmalle(); aku3.lisaaIdOhjelmalle(); 
    int id1 = aku1.getTreeniohjelmanId(); 
    int id2 = aku2.getTreeniohjelmanId(); 
    Treeni pitsi11 = new Treeni(id1); kerho.lisaa(pitsi11); 
    Treeni pitsi12 = new Treeni(id1); kerho.lisaa(pitsi12); 
    Treeni pitsi21 = new Treeni(id2); kerho.lisaa(pitsi21); 
    Treeni pitsi22 = new Treeni(id2); kerho.lisaa(pitsi22); 
    Treeni pitsi23 = new Treeni(id2); kerho.lisaa(pitsi23); 
    List<Treeni> loytyneet; 
    loytyneet = kerho.annaTreenit(aku3); 
    assertEquals("From: TreeniPaivaKirja line: 111", 0, loytyneet.size()); 
    loytyneet = kerho.annaTreenit(aku1); 
    assertEquals("From: TreeniPaivaKirja line: 113", 2, loytyneet.size()); 
    assertEquals("From: TreeniPaivaKirja line: 114", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: TreeniPaivaKirja line: 115", true, loytyneet.get(1) == pitsi12); 
    loytyneet = kerho.annaTreenit(aku2); 
    assertEquals("From: TreeniPaivaKirja line: 117", 3, loytyneet.size()); 
    assertEquals("From: TreeniPaivaKirja line: 118", true, loytyneet.get(0) == pitsi21); 
  } // Generated by ComTest END
}