package treeniPaivaKirja.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import treeniPaivaKirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.03.25 20:50:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreenitTest {



  // Generated by ComTest BEGIN
  /** testAnnaTreenit24 */
  @Test
  public void testAnnaTreenit24() {    // Treenit: 24
    Treenit treenit = new Treenit(); 
    Treeni pitsi21 = new Treeni(2); treenit.lisaa(pitsi21); 
    Treeni pitsi11 = new Treeni(1); treenit.lisaa(pitsi11); 
    Treeni pitsi22 = new Treeni(2); treenit.lisaa(pitsi22); 
    Treeni pitsi12 = new Treeni(1); treenit.lisaa(pitsi12); 
    Treeni pitsi23 = new Treeni(2); treenit.lisaa(pitsi23); 
    Treeni pitsi51 = new Treeni(5); treenit.lisaa(pitsi51); 
    List<Treeni> loytyneet; 
    loytyneet = treenit.annaTreenit(3); 
    assertEquals("From: Treenit line: 37", 0, loytyneet.size()); 
    loytyneet = treenit.annaTreenit(1); 
    assertEquals("From: Treenit line: 39", 2, loytyneet.size()); 
    assertEquals("From: Treenit line: 40", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Treenit line: 41", true, loytyneet.get(1) == pitsi12); 
    loytyneet = treenit.annaTreenit(5); 
    assertEquals("From: Treenit line: 43", 1, loytyneet.size()); 
    assertEquals("From: Treenit line: 44", true, loytyneet.get(0) == pitsi51); 
  } // Generated by ComTest END
}